### ISSUE TITLE
Is this possible with assh?

### ISSUE THREAD

**Issue by ashmatadeen** [moul/advanced-ssh-config#100]
I would like to set up my ssh config to connect to a number of servers:
- server1.domain.com
- server2.domain.com
- server3.domain.com
- server4.domain.com
etc

by simply doing
`ssh server[X]`

Connection to all servers are with the same ssh key and same user.
Is this possible with assh?

I have tried this:
```yml
  hosts: 
    "server*":
      Hostname: "%h.domain.com"
      User: ash
      IdentityFile: ~/.ssh/id_ecdsa
```

which errors with:
`FATA[0000] Proxy error: dial tcp [::1]:22: getsockopt: connection refused `

Thanks,
Ash

**Comment by moul** [comment]
Hi @ashmatadeen,

Your configuration should works, however, there is a bug, I'm resolving twice time the `%h` format string

---

**example:**

Using your configuration file:

```console
$ ssh -v server1
[...]
debug1: Executing proxy command: exec assh proxy --port=22 server1.domain.com
[...]
time="2016-02-02T00:09:47+01:00" level=info msg="Host server1.domain.com"
time="2016-02-02T00:09:47+01:00" level=info msg="  HostName server1.domain.com.domain.com"
time="2016-02-02T00:09:47+01:00" level=info msg="  IdentityFile ~/.ssh/id_ecdsa"
time="2016-02-02T00:09:47+01:00" level=info msg="  User ash"
```

**Comment by moul** [comment]
As a temporary fix, you can use this:

```yml
  "server*":
    #Hostname: "%h.domain.com"
    ResolveCommand: "echo %h.domain.com"
    User: ash
    IdentityFile: ~/.ssh/id_ecdsa
```
