### ISSUE TITLE
ssh bar/foo works fine -- ssh bar with default gateway foo fails

### ISSUE THREAD

**Issue by emanelif** [moul/advanced-ssh-config#115]
consider the following config

    foo:
        Hostname: hostA
    bar:
        Hostname: hostB
        Gateways:
            - foo

according to the readme `ssh bar` should work. However the connection times out then,

    Connection timed out during banner exchange

The confusing thing is that `ssh bar/foo` is working fine. Where is my mistake?

**Comment by moul** [comment]
I think you have the same problem than here: https://github.com/moul/advanced-ssh-config/issues/102

Can you try to update your config file to this and try again:

```yaml
foo:
  Hostname: hosta
bar:
  # Hostname: hostb            # comment this line
  ResolveCommand: echo hostb   # add this line
  Gateways:
  - foo  
```
