### ISSUE TITLE
Multiple LocalForward options

### ISSUE THREAD

**Issue by bvleur** [moul/advanced-ssh-config#119]
I would like to open 2 TCP tunnels when connected to a single host.

Using configuration like:
```
hosts:
  myhost:
    HostName: 1.2.3.4
    LocalForward: "3307 127.0.0.1:3306"
    LocalForward: "8080 10.1.2.3:80"
```

is not supported and silently (!) only uses the last `LocalForward` option.

It would be great if multiple forwards are accepted like (option *a*):
```
    LocalForward:
      - "3307 127.0.0.1:3306"
      - "8080 10.1.2.3:80"
```

I personally would like a configuration like (option *b*):
```
    LocalForward:
      3307: "127.0.0.1:3306"
      8080: "10.1.2.3:80"
```

(because a mapping still allows for inheritance and overriding specific keys)

**Comment by moul** [comment]
HI @bvleur, thank you for reporing,

I also prefer the option B, I need to give some tests here, I will probably have limitaions with the yaml specifications

**Comment by scoates** [comment]
FWIW, this hack works in the meantime (it's *ugly* but it works):

```yaml
hosts:
  myhost:
    HostName: 1.2.3.4
    LocalForward: "3307 127.0.0.1:3306\n  LocalForward: 8080 10.1.2.3:80"
```

**Comment by moul** [comment]
Hi, you can now use one (string) or multiple (list) `LocalForward` per hosts

Can you give a try ?

PS: I decided to implement the `option A`, because it's more generic, I also applied this change to every single-or-multiple options

**Comment by pschmitt** [comment]
Hi,

what would be the correct way to set a `LocalForward` config rule that does the same as 
`-L '*:10051:localhost:10051'` would on the command line?

**Comment by moul** [comment]
Hi @pschmitt, `LocalForward` accepts strings or array of strings, so in flexible yaml it can be one of the three following methods: 

```yaml
hosts:
  aaa:
    LocalForward: '*:10051:localhost:10051'
  bbb:
    LocalForward:
    - *:10051:localhost:10051
    - *:10052:localhost:10052
  ccc:
    LocalForward: ['*:10051:localhost:10051', '*:10052:localhost:10052']
```
