### ISSUE TITLE
Empty gateway directories being created in current working directory

### ISSUE THREAD

**Issue by stk0vrfl0w** [moul/advanced-ssh-config#124]
When trying to access a machine that uses a gateway, assh always creates an empty directory named after each of the gateways it had tried in the current working directory.  

So, for the example assh.yml config file below, if I try to ssh to frankbastion and it goes through gateway3, there will be empty directories called gateway1, gateway2 and gateway3 created in the current working directory.  Is there an option to disable directory creation?  It's not necessary for my use case and pollutes my working spaces everywhere.

```yaml

    defaults:
        LogLevel: error
        ForwardAgent: yes
        ServerAliveInterval: 30
        StrictHostKeyChecking: no
        UserKnownHostsFile: /dev/null

    hosts:

        gateway*:
            Hostname: "%h.mycompany.io"
            Inherits:
                - control-template

        frankbastion:
            DynamicForward: 5555
            Hostname: frank.mycompany.io
            Inherits:
                - gw-proxy

        beansbastion:
            DynamicForward: 6666
            Hostname: beans.mycompany.io
            Inherits:
                - gw-proxy


    templates:

        control-template:
            ControlMaster: auto
            ControlPath: ~/.ssh/%h_control.sock

        gw-proxy:
            ProxyCommand: nc -q0 %h 22
            Gateways:
                - gateway1
                - gateway2
                - gateway3

```
