### ISSUE TITLE
Allow port fallback similar to gatways

### ISSUE THREAD

**Issue by rothgar** [moul/advanced-ssh-config#126]
For some hosts I am able to connect directly to them when I'm on my lan and need to use a non-standard port when going through the wan (firewall port mapping) It'd be nice to have something like this in my assh.yml to allow me to connect to the same host no matter where I am.

```
host:
    Hostname: host1
    Port:
        - 22
        - 2222
```
Maybe this is already possible with gateways but I haven't tested it yet and may be more confusing when setting up.

**Comment by moul** [comment]
I like the idea, but I would push it to the next level by allowing a "meta hosts" which have a full configuration fallback:

```yaml
hosts:
  hosta:
    configs:
    - hosta.local
    - hosta.remote
    - hosta.via-gateway
  hosta.local:
    hostname: host1
    port: 22
  hosta.remote:
    hostname: host1
    port: 2222
  hosta.via-gateway
    hostname: 1.2.3.4
    port: 22
    gateway: my-gateway
```
