### ISSUE TITLE
Add a timeout when bruteforcing gateways, again

### ISSUE THREAD

**Issue by Skrupellos** [moul/advanced-ssh-config#132]
#12 since was closed, the feature seems to have disappeared or is not available for `direct` gateway. Pleas add a configurable timeout. `ConnectTimeout` won't do here, since it would prevent any connection (even over the last gateway in the list) on a really crappy connection.

``` yaml
  jump1:
    DefaultGwTimeout: 10

  jump2:
    DefaultGwTimeout: 10

  dst:
    Gateways:
    - direct/5
    - jump1
    - jump2/5
```

Try to connect
1. 5 seconds directly
2. 10 seconds to jump1
3. 5 seconds to jump2

**Comment by moul** [comment]
Hi @Skrupellos, thank you for your feedback,

👍, will do

**Comment by cnf** [comment]
Hi,

is this included in 2.5.0 ?

**Comment by moul** [comment]
Hi @cnf, no sorry, I will move it to a new v2.6.0 milestone, but I now know how to implement it

**Comment by cnf** [comment]
Nice! it's a very nice tool (and thanks for building it!) but waiting for gateway timeouts gets a bit frustrating :P

**Comment by moul** [comment]
@cnf, look at #132 :)

```yaml
hosts:
  gateways-timeout:
    hostname: 127.0.0.1
    gateways: [gateway1, gateway2, direct, gateway3]

  gateway1:
    ConnectTimeout: 3

  gateway2:
    ConnectTimeout: 1

  gateway3:
    ConnectTimeout: 0
```

```console
$> ssh gateways-timeout
Connection timed out during banner exchange
ERRO[0003] Cannot use gateway 'gateway1': exit status 255
Connection timed out during banner exchange
ERRO[0004] Cannot use gateway 'gateway2': exit status 255
New SSH connection to root@127.0.0.1:22 at 2017-01-06 18:14:48.778992585 +0100 CET
```

`ConnectTimeout` means no timeout
