### ISSUE TITLE
Aliases support

### ISSUE THREAD

**Issue by Skrupellos** [moul/advanced-ssh-config#133]
Add an `Aliases` configuration option. So, instead of writing
```yaml
  example.com:
    HostName: example.com
  
  roleA:
    Inherits:
    - example.com
  
  roleB:
    Inherits:
    - example.com
```
one could write

```yaml
  example.com:
    Aliases:
    - roleA
    - roleB
```
