### ISSUE TITLE
Can support netcat mode?

### ISSUE THREAD

**Issue by Tomohiro** [moul/advanced-ssh-config#146]
OpenSSH 5.4 has a "netcat mode". See [OpenSSH/Cookbook/Proxies and Jump Hosts - Wikibooks, open books for an open world](https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Proxies_and_Jump_Hosts#ProxyCommand_with_Netcat).

Example of netcat mode:

```
$ ssh -o ProxyCommand="ssh -W %h:%p jumphost.example.org" server.example.org
```

**Comment by moul** [comment]
Hi @Tomohiro, thank you for this question,

Yes !

I just updated the `README.md` with a better explanation and new examples of Gateways usages (see ef6b2c88a7d619b2ae5fd2b2f12ae18a7b1cfd5e).

---

Let's consider this example

```yaml
  tomohiro-a:
    HostName: 1.2.3.4

  tomohiro-b:
    HostName: 5.6.7.8
    Gateways:
      - tomohiro-a
```

`ssh tomohiro-b` is the equivalent of `ssh -o ProxyCommand="ssh -W %h:%p tomohiro-a" 5.6.7.8`
