### ISSUE TITLE
Gateways property does not apply on inheritance or regex matches

### ISSUE THREAD

**Issue by mohdjas** [moul/advanced-ssh-config#147]
Hello,

The `Gateways` property seems to be ignored in a few cases.

For example, this works as expected:

``` yaml
templates:
  test-template:
    Gateways:
      - bastion-pub

hosts:
  foo-vpc:
    HostName: 1.2.3.4
    Inherits:
      - test-template

  bar-vpc:
    HostName: 2.3.4.5
    Inherits:
      - test-template
```

To reduce repetition, I moved the 'Inherits' field to a regex match:

``` yaml
templates:
  test-template:
    Gateways:
      - bastion-pub

hosts:
  foo-vpc:
    HostName: 1.2.3.4

  bar-vpc:
    HostName: 2.3.4.5

  "*-vpc":
    Inherits:
      - test-template
```

This did not work. Using verbose mode on SSH, I found out that connections to `foo-vpc` and `bar-vpc` were being attempted directly instead of via the `bastion-pub` gateway. However, if I try `ssh foo-vpc/bastion-pub` it works fine.

I tried the following as well but it didn't work either:

``` yaml
hosts:
  foo-vpc:
    HostName: 1.2.3.4

  bar-vpc:
    HostName: 2.3.4.5

  "*-vpc":
    Gateways:
      - bastion-pub
```

I tried a few more combinations, and found that in the two non-working configs above, only the `Gateways` field seemed to not be taken into consideration.

Is there something I am missing or misunderstanding about the regex matching or the inheritance aspect?

**Comment by moul** [comment]
Hi @mohdjas, thank you for your feedback

this is related to things I recently changed, can you give me the result of the two following commands:

* `assh --version`
* `assh info`

Thanks

**Comment by mohdjas** [comment]
Hi @moul, here's the output of the two commands:

```bash
~ assh info
Debug mode (client): false
CLI Path: /usr/bin/assh
Go version: go1.6.1
OS/Arch: linux/amd64

RC files:
- ~/.ssh/assh.yml
- ~/.ssh/assh.d/pub.yml
- ~/.ssh/assh.d/ts.yml
- ~/.ssh/assh.d/vpc.yml

Statistics:
- 100 hosts
- 4 templates
- 4 included files
```

```bash
~ assh --version
assh version 2.3.0 (HEAD)
```

I installed assh from the DEB file on the downloads page, if that helps any. I tried installing using Go, but I was getting some dependency errors so couldn't proceed that route.

Let me know if you need any other info. :)

**Comment by moul** [comment]
Ok, I got it, actually you try to get rules from multiple matching rules at once, however, assh only works with one rule at a time (the most maching one)

My first idea is to keep the current system, because I think that an host matching multiple rules may introduce new bugs and make the debugging very complex

What do you think about adding something like this instead:

```yaml
templates:
  test-template:
    Gateways:
      - bastion-pub
    ApplyOn:
      - "*-vpc"

hosts:
  foo-vpc:
    HostName: 1.2.3.4

  bar-vpc:
    HostName: 2.3.4.5
```

?

**Comment by mohdjas** [comment]
> Ok, I got it, actually you try to get rules from multiple matching rules at once, however, assh only works with one rule at a time (the most maching one)

This seems to apply to `Gateways` only (there might be more, but I've only had limited experience with assh so far). For example, the following config picks up `Port` but not `Gateways`:

```yaml
hosts:
  foo-vpc:
    HostName: 1.2.3.4

  bar-vpc:
    HostName: 2.3.4.5

  "*-vpc":
    Port: 42
    Gateways:
      - bastion-pub
```
Currently I'm using the first config in my initial post so I'm not blocked. The only downside so far (and not too major either) is that I can't change the config in one spot to apply to all (but that's nothing that's can't be fixed by Search and Replace ;)).

IMHO, the `ApplyOn` field would be a little confusing since people would expect the wildcard hostnames to pick the fields up.

I don't know how assh works (I haven't gone through the entire codebase) but based on trial-and-error I can see that the generated SSH config file will have hostname sets based on the hosts defined in  the YAML files. For wildcard entries, would it be possible to apply the matching entries into the SSH config files?

For example:
```yaml
hosts:
  foo-vpc:
    HostName: 1.2.3.4

  bar-vpc:
    HostName: 2.3.4.5

  "*-vpc":
    Gateways:
      - bastion-pub
```
would generate the SSH config entries:
```
Host *-vpc
  # Gateways: [bastion-pub]

Host foo-vpc
  # HostName: 1.2.3.4
  # Gateways: [bastion-pub]

Host bar-vpc
  # HostName: 1.2.3.4
  # Gateways: [bastion-pub]
```

Could this work? This would keep the same read rules from earlier when no regex is used, and there's no additional field involved, either. This would of course make the final SSH config file bigger, but then assh is managing it so that shouldn't be a problem, right?
