### ISSUE TITLE
Can assh generate full assh binary path in ~/.ssh/config?

### ISSUE THREAD

**Issue by EvianZhow** [moul/advanced-ssh-config#148]
I'm using SourceTree to manage my git repos which push and pull through SSH. 
After every config YAML changes, I re-generate with `assh build > ~/.ssh/config`. 
The last line `ProxyCommand` start with **assh** instead of **the full assh binary path**, and that cause SourceTree failed to find assh when doing network operations. I have to manually append the full prefix every time I re-genrate the config. I understand that it is caused by the alias, because SourceTree internally use ssh by default, but what if my GitLab machine is behind some relay node and want to access through assh?
Also, this problem occurs when user choose a different install location instead of Homebrew's `/usr/local/bin`, and this may also brick SourceTree or any other apps. 
So I suggest that we could add a field which named like **BIN_PATH** to YAML config, and generate the full assh binary path instead of the barely assh one?

Give me a thumbs-up if you face the same pain :)

**Comment by moul** [comment]
👍 :)

**Comment by moul** [comment]
You can now add this to your assh.yml file

```yaml
hosts:
  blahblah:
    blah: blah

defaults:
  blah: blah

includes:
- ~/.ssh/blah.yml

ASSHBinaryPath: ~/mbin/assh  # full or relative path to the assh binary
```

---

This feature will be shipped with the next release, you can already try it by installing assh from GIT
