### ISSUE TITLE
Document Usecase for NoControlMasterMkdir=false / Default: NoControlMasterMkdir=true?

### ISSUE THREAD

**Issue by Skrupellos** [moul/advanced-ssh-config#173]
For now, I don't see the use case for ControlMaster directory creation. Where does it have an advantage over:

``` yaml
defaults:
    NoControlMasterMkdir: true
    ControlPath: ~/.ssh/cm/%C.sock
    ControlMaster: auto
```

As @stk0vrfl0w already mentioned in #124, the default settings polluted my filesystem with empty directories. As it it not obvious where those directories come from, I would suggest that `NoControlMasterMkdir` is set to `true` by default (or an `ControlMasterMkdir` option is set to `false` by default). Second, it should be documented why there is an option to create those directories and how they are created.
