### ISSUE TITLE
bad configuration options

### ISSUE THREAD

**Issue by MiLk** [moul/advanced-ssh-config#178]
Recently, I have a lot of errors when using `assh` and I need to rebuild the config to fix it.

I have the following error message:

```
/Users/user/.ssh/config: line 14: Bad configuration option: 3.233,
/Users/user/.ssh/config: terminating, 1 bad configuration options
ERRO[0000] Cannot use gateway 'bastion': exit status 255
FATA[0000] Proxy error: No such available gateway
ssh_exchange_identification: Connection closed by remote host
/Users/user/.ssh/config: line 14: Bad configuration option: 3.233,
/Users/user/.ssh/config: terminating, 1 bad configuration options
```

How can I get more helpful details?

My config looks like:

```
Host 10.10.*
  IdentityFile ~/.ssh/REDACTED
  Port 22
  # Inherits: [REDACTED-template]
  # Gateways: [bastion]

Host bastion
  IdentityFile ~/.ssh/REDACTED
  Port 22
  # HostName: bastion.REDACTED
  # Inherits: [REDACTED-template]
```

It seems to happen every time I log into a new host.

**Comment by moul** [comment]
Hi @MiLk, I recently changed the default behavior of the parser to make it more reliable for *array* fields, I have probably missed some tests :#

Can you give me your source config file in Yaml format (`~/.ssh/assh.yml`) ?

**Comment by MiLk** [comment]
My `~/.ssh/assh.yml`:
```yaml
defaults:
  ForwardAgenti: no
  GSSAPIAuthentication: no
  IdentityFile: ~/.ssh/id_rsa

includes:
- ~/.ssh/assh.d/perso.yml
- ~/.ssh/assh.d/work.yml
- ~/Dev/PROJECT/assh.yml
```

`~/.ssh/assh.d/perso.yml`
```yaml
hosts:
  gw:
    Hostname: REDACTED
    Port: 22
    User: gw
    IdentityFile: ~/.ssh/REDACTED
    ForwardAgent: yes
  REDACTED:
    Hostname: REDACTED
    User: centos
    Port: 22
    IdentityFile: ~/.ssh/REDACTED
```

`~/.ssh/assh.d/work.yml`
```yaml
hosts:
  "172.16.*":
    IdentityFile: ~/.vagrant.d/insecure_private_key
    ForwardAgent: yes

  bastion.local:
    Hostname: 172.16.0.10
    Inherits:
    - vagrant-template

  web1.local:
    Hostname: 172.16.0.100
    Inherits:
    - vagrant-template
    Gateways:
    - bastion.local

templates:
  vagrant-template:
    Port: 22
    User: REDACTED
    IdentityFile: ~/.ssh/id_rsa
```

`~/Dev/PROJECT/assh.yml`
```yaml
templates:
  PROJECT-template:
    Port: 22
    IdentityFile: ~/.ssh/REDACTED

hosts:
  bastion:
    HostName: REDACTED
    StrictHostKeyChecking: no
    Inherits:
    - PROJECT-template

  "10.10.*":
    StrictHostKeyChecking: no
    Inherits:
    - PROJECT-template
    Gateways:
    - bastion
```

The `~/.ssh/assh_known_hosts` file contains one row with `10.10.3.233` (it's always that row with is referenced in the error message), but nothing seem off in the file.
