### ISSUE TITLE
Configs for same hosts should be merged

### ISSUE THREAD

**Issue by ocean90** [moul/advanced-ssh-config#213]
**Use case:** You get a config file from your hosting provider which includes IP and port settings:

In `assh.d/hosting/example.yml`
```
hosts:
  example.org:
    Hostname: 236.76.138.168
    Port: 2221
```

Since you're using a different login name for this host you have to use a custom config:

In `assh_personal.yml`:
```
hosts:
  example.org:
     User: dominik
```

The corresponding `assh.yml` looks like this:

```
includes:
  - ~/.ssh/assh.d/*/*.yml
  - ~/.ssh/assh_personal.yml
```

**Expected output:**

```
➜  ~ assh config list | grep example.org
    example.org -> dominik@236.76.138.168:2221
```

**Actual output:**
```
➜  ~ assh config list | grep example.org
    example.org -> dominik@[hostname_not_specified]:22
```

Also tried with `Inherits` but it produces the same output.
```
  example.org:
    User: dominik
    Inherits:
      - example.org
```

**Comment by ivomarino** [comment]
@ocean90 have you rebuilt `~/.ssh/config` via `assh config build > ~/.ssh/config`?

**Comment by moul** [comment]
Hi @ocean90,

I think I can handle it from the config loader itself, but it may be better to keep the choice to the user, and maybe we can use the built-in `yaml` advanced features

If you have some time to give a try, maybe this can help you while allowing people to keep the current behavior if wanted

* http://yaml.org/type/merge.html
* http://yaml.org/YAML_for_ruby.html#merge_key

**Comment by ocean90** [comment]
@moul Thanks for links. I could get it kinda working.

**Config:**
```yaml
hosts:
  example.org: &example-org
    Hostname: 236.76.138.168
    Port: 2221

  example.org:
     <<: *example-org
     User: foo
```

**Output:**
```
➜  ~ assh config list | grep example.org
    example.org -> foo@236.76.138.168:2221
```

Sadly this doesn't work if `example.org: &example-org` is in another file like `assh.d/hosting/example.yml`. :(

> WARN[0000] Cannot include "~/.ssh/assh_personal.yml": yaml: unknown anchor 'example-org' referenced
