### ISSUE TITLE
Add a way to disable notifications per host

### ISSUE THREAD

**Issue by moul** [moul/advanced-ssh-config#234]
**Expected**: being able to configure notifications globally (`defaults`), while disabling the behavior on certain hosts.

```yaml
github.com:
  Hooks: none

defaults:
  Hooks:
    OnConnect:
    - notify blah blah
```

**Problem**: the `Hooks` option is always merged, so it's impossible to disable notifications on some host as soon as the `defaults.Hooks` is set

---

Ideas:
* do not "merge" the `Hooks` options so we can set an empty list
* add support for `<host>.Hooks = off`

Continues #231
