### ISSUE TITLE
Possibility to disable automatic rewrite of .ssh/config or include regular SSH config

### ISSUE THREAD

**Issue by diehlsa** [moul/advanced-ssh-config#239]
Hello,

I need to combine SSH configurations from two different sources. Both are created automatically (from a database or git repo). One of the sources uses assh, the other creates a regular ssh config.

Is there a way to include the regular config in assh or at least prevent assh from automatically rewriting the `.ssh/config` file, so I can manually combine the two?

Thanks for any help!
Sarah

**Comment by moul** [comment]
Hi @diehlsa,

*OpenSSH* added an `Include` directive in version *7.3p1*, I probably broke the support because `assh` interprets the `include` directive too. I need to check a little bit more, but I can clearly support including standard ssh files, using the *OpenSSH* directive or appending the other files directly when generating the configuration file.

I will also add an option to disable the automatic rewrite

**Comment by diehlsa** [comment]
@moul Thanks for looking into this!

**Comment by moul** [comment]
You can now disable automatic generation by building the configuration file like this:

    assh config build --no-automatic-rewrite > ~/.ssh/config

This way, `assh` will only warn you if your configuration file is outdated

---

I will add a new hook that will be called just after the config file generation so we can imagine something like this:

```yaml
defaults:
  hooks:
    AfterConfigBuild:
      - exec "cat ~/.ssh/config.secondary >> ~/.ssh/config"
```
It will probably make more workflows available too

**Comment by diehlsa** [comment]
Great, thanks a lot for the swift reaction :-). The hook looks perfect.

**Comment by moul** [comment]
@diehlsa, you can now add this:

```yaml
defaults:
  hooks:
    AfterConfigWrite:
    - 'exec cat /path/to/your/secondary/ssh/config >> {{.SSHConfigPath}}'
```
