### ISSUE TITLE
Use ResolveCommand hostname when creating ssh config

### ISSUE THREAD

**Issue by herver** [moul/advanced-ssh-config#244]
Hello, 

I'm trying to use assh in combination with kerberos authentication, and there is a small issue, here's my configuration:
```
hosts:
  "osd.[0-9]*.ceph1":
    ResolveCommand: /bin/sh -c "ceph --cluster ceph1 osd find $(echo %h | sed -E 's/osd.([0-9]+).ceph1/\1/') | jq -r .crush_location.host"
```

The `ResolveCommand` returns the correct hostname, but when ssh is connecting to the machine, it mentions the hostname I type on the command line, and not the resolved one. This prevents SSH from using Kerberos authentication because the hostname provided by ASSH doesn't match any entry on the Kerberos database.

```
[...]
debug1: Host 'osd.12.ceph1' is known and matches the ECDSA host key.
[...]
debug1: Next authentication method: gssapi-with-mic
debug1: Unspecified GSS failure.  Minor code may provide more information
Server not found in Kerberos database
```

**Comment by moul** [comment]
Hi @herver, thank you for your feedback

Can you confirm me that the expected behavior is that `assh` generates the result of the `ResolveCommand` as `Hostname` in the generated `.ssh/config` host?

Example:

```yaml
hosts:
  "osd.[0-9]*.ceph1":
    ResolveCommand: /bin/sh -c "ceph --cluster ceph1 osd find $(echo %h | sed -E 's/osd.([0-9]+).ceph1/\1/') | jq -r .crush_location.host"
```

```ini
Host osd.42.ceph1
  Hostname: 1.2.3.4 (result of the ResolveCommand)

Host osd.1337.ceph1
  Hostname: 5.6.7.8 (result of the ResolveCommand)
```
