### ISSUE TITLE
assh config build drops extra IdentityFile parameters.

### ISSUE THREAD

**Issue by bdmorin** [moul/advanced-ssh-config#248]
IdentityFile: /Users/2/.ssh/2/id_rsa
 
Here is a snippet of my assh.yml file. 
```
defaults:
    ControlMaster: auto
    ControlPath: ~/tmp/.ssh/%h-%p-%r.sock
    ControlPersist: yes
    IdentityFile: /Users/1/.ssh/1/id_rsa
    IdentityFile: /Users/2/.ssh/2/id_rsa
    IdentityFile: /Users/3/.ssh/3/id_rsa
    UseKeychain: yes
    Port: 22
    StrictHostkeychecking: no
    Forwardx11: no
    ForwardAgent: yes
    Protocol: 2
    ServerAliveInterval: 5
```
When I `assh config build` it only uses 1 IdentityFile. I add them back in manually, so it's not a huge deal, and I don't know if this is operating as expected or if this is a bug. You can support multiple IdentityFile(s) in a config.

```
Host *
  ControlMaster auto
  ControlPath ~/tmp/.ssh/%h-%p-%r.sock
  ControlPersist yes
  ForwardAgent yes
  ForwardX11 no
  IdentityFile /Users/1/.ssh/1/id_rsa
  Port 22
  Protocol 2
  ServerAliveInterval 5
  StrictHostKeyChecking no
  UseKeychain yes
  ProxyCommand assh connect --port=%p %h
```

**Comment by moul** [comment]
Hi @bdmorin,

This is due to a limitation in the YAML protocol which only supports one unique entry per key, but it's easily bypassable by replace, this:

```yaml
    IdentityFile: /Users/1/.ssh/1/id_rsa
    IdentityFile: /Users/2/.ssh/2/id_rsa
    IdentityFile: /Users/3/.ssh/3/id_rsa
```

to this:

```yaml
    IdentityFile:
      - /Users/1/.ssh/1/id_rsa
      - /Users/2/.ssh/2/id_rsa
      - /Users/3/.ssh/3/id_rsa
```

---

Example here:
* [`assh.yml`](https://github.com/moul/advanced-ssh-config/commit/27e16391e6a8317d7d83a39ec5b426d5b4407c94#diff-01261f3447b8e0745434963830e84c70)
* [generated `ssh_config`](https://github.com/moul/advanced-ssh-config/commit/27e16391e6a8317d7d83a39ec5b426d5b4407c94#diff-bb745dbf3f479da49b83a533d2458ce3)

Thank you for your feedback
