### ISSUE TITLE
Hooks doesn't working on osx

### ISSUE THREAD

**Issue by ghost** [moul/advanced-ssh-config#262]
Hello, i work on osx sierra version 10.12.6. I have installed assh (v2.6.0) with brew.

my assh file: 
```yaml
hosts:
  my_host:
    User: my_user
    Inherits: my_template

templates:
  my_template:
    HostName: my_hostname
    IdentityFile: ~/.ssh/my_key

defaults:
  ControlMaster: auto
  ControlPath: ~/tmp/cm/%h-%p-%r.sock
  ControlPersist: yes
  Hooks:
    BeforeConnect:
      # Log internal information to a file
      - 'exec echo {{.}} | jq . >> ~/last_connected_host.txt'

      # Alert me with a Desktop notification
      - notify New SSH connection to {{.Host.Prototype}} at {{.Stats.ConnectedAt}}

      # Write the host prototype to the terminal stderr
      - write New SSH connection to {{.Host.Prototype}}
```

SSH connection work fine but i don't have notification. ~/last_connected_host.txt is created but file is empty.

I don't understand.
Thanks for your help.

**Comment by robinbowes** [comment]
I'm having a problem with hooks on OSX too.

I'm testing with this fragment:

```
defaults:
  # Defaults are applied to each hosts
  ControlMaster: auto
  # ControlMasterMkdir: true
  ControlPath: ~/tmp/.ssh/cm/%h-%p-%r.sock
  ControlPersist: yes
  Hooks:
    AfterConfigWrite:
      - "exec echo {{.SSHConfigPath}}"
      - "exec cat ~/.ssh/extra.config >> {{.SSHConfigPath}}"
  IdentityFile:
    - ~/.ssh/id_rsa
  LogLevel: ERROR
  Port: 22
```

When I ssh to a host, I get:
```
  ssh lin001
WARN[0000] Unable to remove tempfile: /Users/robin/.ssh/config372656303
Last login: Wed Jul 18 09:38:45 2018 from XXX
[robin@lin001 ~]$
```

The ~/.ssh/config ends up with this content:

```
Host *
  ControlMaster auto
  ControlPath ~/tmp/.ssh/cm/%h-%p-%r.sock
  ControlPersist yes
  IdentityFile ~/.ssh/id_rsa
  LogLevel ERROR
  Port 22
  ProxyCommand /usr/local/bin/assh connect --port=%p %h
  # Hooks: {"AfterConfigWrite":["exec echo {{.SSHConfigPath}}","exec cat ~/.ssh/extra.config \u003e\u003e {{.SSHConfigPath}}"]}
```

Am I doing something wrong, or is this a bug?
