### ISSUE TITLE
IdentityFile data missing from Hook template vars

### ISSUE THREAD

**Issue by colebrumley** [moul/advanced-ssh-config#264]
I would like to use a `BeforeConnect` hook to dynamically pull my `IdentityFile` from a remote store (Vault in this case) as needed before connecting, but the `IdentityFile` array is empty. Is there a reason this info isn't available at the `BeforeConnect` stage?

My config file looks like this:
```yaml
defaults:
  ServerAliveInterval: 30
  Port: 22
  ConnectTimeout: 10
  ForwardX11: no
  ControlMaster: auto
  ControlPath: ~/.ssh/cm/%h-%p-%r.sock
  ControlPersist: 10m
  Hooks:
    AfterConfigWrite:
      - 'exec echo "# date: $(date)" >> {{.SSHConfigPath}}'
    BeforeConnect:
      - exec "VAULT_ADDR=https://vault.services vault read -field=content secret/keys/{{.Host.IdentityFile[0]}} > ~/.ssh/{{.Host.IdentityFile[0]}}.pem && chmod 0600 ~/.ssh/{{.Host.IdentityFile[0]}}.pem"
includes:
  - ~/.ssh/assh.d/*.yml
  - ~/.ssh/assh.d/*.yaml
```
