### ISSUE TITLE
Port number not changing with multiple inherits

### ISSUE THREAD

**Issue by salt-lick** [moul/advanced-ssh-config#268]
I noticed that if you include multiple inheritances, any port number configuration is not picked up or applied to the connection.

Setup:

```yaml
 local_box:
    Hostname: 1.2.3.4
    IdentityFile: [redacted]
    Inherits:
    - root_user
    - port_change


templates:
  root_user:
    User: root
  port_change:
    Port: 87
```

Debug Output:

```bash
INFO[0000] Host local_box
INFO[0000]   IdentityFile [redacted]
INFO[0000]   Port 22
INFO[0000]   User root
INFO[0000]   # HostName: 1.2.3.4
INFO[0000]   # Inherits: [root_user, port_change]
```

As you see, the port is not being overwritten with the config from the inheritance and the connection is not made because of the port misconfiguration. 

If I add Port: 87 to the root_user template, the connection is made correctly. 

```yaml
 local_box:
    Hostname: 1.2.3.4
    IdentityFile: [redacted]
    Inherits:
    - root_user

templates:
  root_user:
    User: root
    Port: 87
```

Thoughts? Am I just doing something wrong?

Thanks!
